[build]
  # Comando que Netlify ejecutar치 para generar la carpeta de producci칩n
  command = "npm run build"
  # Carpeta que contiene los archivos est치ticos tras build
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-vite"

# Si tu app es un SPA (Single Page Application), a침ade esto para que
# todas las rutas se redirijan al index.html:
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
