export const NAV_LINKS = [
  { href: "#sobre-mi", langKey: "navAbout", text: "Sobre Mí" },
  { href: "#proyectos", langKey: "navProjects", text: "Proyectos" },
  { href: "#experiencia", langKey: "navExperience", text: "Experiencia" },
  { href: "#habilidades", langKey: "navSkills", text: "Habilidades" },
  { href: "contact", langKey: "navContact", text: "Contacto" }
];

export const LANGUAGES = [
  {
    code: 'es',
    flag: '🇪🇸',
    names: { es: 'Español', en: 'Spanish' }
  },
  {
    code: 'en',
    flag: '🇬🇧',
    names: { es: 'Inglés',  en: 'English' }
  }
];



export const translations = {
  es: {
    contactTitlePage: "Marcos Díaz Oliva - Contacto",
    navName: "Marcos Díaz Oliva",
    navAbout: "Sobre Mí",
    navProjects: "Proyectos",
    navExperience: "Experiencia",
    navSkills: "Habilidades",
    navContact: "Contacto",
    navAboutMobile: "Sobre Mí",
    navProjectsMobile: "Proyectos",
    navExperienceMobile: "Experiencia",
    navSkillsMobile: "Habilidades",
    navContactMobile: "Contacto",
    heroAltImage: "Foto personal",
    heroTitle: "Hola, soy Marcos",
    heroSubtitle: "Gestor de Proyectos Informáticos",
    heroContactButton: "Contáctame",
    aboutTitle: "Sobre Mí",
    aboutParagraph1: "Experiencia inicial en proyectos reales de desarrollo y gestión de equipos. Lideré el desarrollo Backend en Valuat, logrando una mejora de hasta el 50% en el rendimiento de los endpoints respecto a la tecnología anterior y hasta un 30% en las llamadas a base de datos. Como gestor de proyectos, presto servicio a dos Subdirecciones Generales, gestionando equipos de 3 empresas distintas.",
    aboutParagraph2: "[Añade más detalles si lo deseas, como tus intereses, hobbies relevantes o tu filosofía de trabajo.]",
    projectsTitle: "Proyectos Destacados",
    project1AltImage: "[Imagen de Proyecto 1]",
    project1Title: "Servicio web de Tests",
    project1Desc: "Desarrollado con Laravel, PHP, MySQL, MongoDB.",
    project2AltImage: "[Imagen de Proyecto 2]",
    project2Title: "Web scripting para Estadística de Datos",
    project2Desc: "Desarrollado con Python, Xampp, MySQL.",
    project3AltImage: "[Imagen de Proyecto 3]",
    project3Title: "Simulación Dispositivo IoT",
    project3Desc: "Desarrollado con Python, Google Cloud, HTML5, CSS3, JS, MariaDB.",
    projectSeeMore: "Ver más",
    projectSourceCode: "Código Fuente",
    experienceTitle: "Experiencia Profesional",
    exp1Title: "Gestor de proyectos informáticos - Ministerio de Vivienda y Agenda Urbana",
    exp1Dates: "Octubre 2024 - Actualidad",
    exp1Task1: "Coordino 4 equipos de trabajo pertenecientes a 3 empresas distintas en materia de desarrollo, mantenimiento y soporte que prestan servicio a 2 Subdirecciones Generales.",
    exp1Task2: "Participo en la mejora de procesos mediante la implementación de metodologías que permiten un mayor control y eficiencia ante las tareas de desarrollo, soporte y mantenimiento de los distintos equipos de trabajo.",
    exp1Task3: "Gestiono las acciones necesarias para el mantenimiento de los sistemas en colaboración con el equipo especializado en sistemas y comunicaciones.",
    exp1Task4: "Analizo las herramientas y soluciones actuales para encontrar mejoras a implementar en los sistemas en relación, mayoritariamente, al rendimiento y la experiencia de usuario.",
    exp1Task5: "Diseño informes que permiten una visualización general práctica de cada uno de los sistemas informáticos y equipos gestionados.",
    exp1Task6: "Elaboro estadísticas haciendo uso de la herramienta de Google Analytics, como parte de la gestión del sistema con información anualizada y la elaboración de informes personalizados.",
    exp2Title: "Analista Programador Backend - Valuat",
    exp2Dates: "Noviembre 2021 - Febrero 2023",
    exp2Task1: "Implementé la metodología de trabajo Scrum con desarrollos en sprints de dos semanas que permitió una mayor eficiencia y rapidez del mismo.",
    exp2Task2: "Mejoré la eficiencia del sistema BackEnd hasta un 35% en su conjunto respecto al sistema antiguo, a partir del análisis y diseño.",
    exp3Title: "Gestor de Sistemas Informáticos en Prácticas - Instituto Nacional de Administración Pública",
    exp3Dates: "Junio 2024 - Octubre 2024",
    exp3Task1: "Formación orientada a la práctica",
    exp3Task2: "Curso en Gobernanza de datos e igualdad",
    skillsTitle: "Habilidades",
    skillsTechTitle: "Habilidades Técnicas",
    skillsOtherTech: "[Otra Habilidad]",
    skillsLangTitle: "Idiomas",
    skillsLangSpanish: "Español:",
    skillsLangSpanishLevel: "Nativo",
    skillsLangEnglish: "Inglés:",
    skillsLangEnglishLevel: "Fluido",
    skillsLangOther: "[Otro Idioma]:",
    skillsLangOtherLevel: "[Nivel]",
    skillsToolsTitle: "Herramientas",
    skillsOtherTool: "[Otra Herramienta]",
    skillsSoftTitle: "Habilidades Blandas",
    skillsSoftComm: "Comunicación",
    skillsSoftTeam: "Trabajo en equipo",
    skillsSoftProblem: "Resolución de problemas",
    skillsSoftAdapt: "Adaptabilidad",
    contactTitle: "Contacto",
    contactIntro: "¿Interesado/a en saber más? ¡No dudes en contactarme!",
    contactDownloadPrompt: "También puedes descargar mi CV:",
    contactMail: "Contáctame",
    contactDownloadButtonES: "Descargar CV",
    contactDownloadButtonEN: "Descargar CV (Inglés)",
    footerRights: "© 2025 Marcos Díaz Oliva. Todos los derechos reservados.",
    contactFormTitle: "Ponte en Contacto",
    contactFormIntro: "¿Tienes alguna pregunta o propuesta? Rellena el formulario.",
    contactFormLabelName: "Nombre completo",
    contactFormInputName: "Tu nombre y apellidos",
    contactFormLabelMail: "Correo electrónico",
    contactFormInputMail: "tu@email.com",
    contactFormLabelPhone: "Número de teléfono",
    contactFormLabelOptional: "(Opcional)",
    contactFormInputPhone: "+34 600 000 000",
    contactFormLabelMessage: "Mensaje",
    contactFormInputMessage: "Escribe aquí tu consulta o mensaje...",
    contactFormSend: "Enviar",
    themeLight: "Claro",
    themeDark: "Oscuro",
    themeSystem: "Sistema",
},
  en: {
    contactTitlePage: "Contact - Marcos Díaz Oliva",
    navName: "Marcos Díaz Oliva",
    navAbout: "About Me",
    navProjects: "Projects",
    navExperience: "Experience",
    navSkills: "Skills",
    navContact: "Contact",
    navAboutMobile: "About Me",
    navProjectsMobile: "Projects",
    navExperienceMobile: "Experience",
    navSkillsMobile: "Skills",
    navContactMobile: "Contact",
    heroAltImage: "Personal photo",
    heroTitle: "Hi, I'm Marcos",
    heroSubtitle: "IT Project Manager",
    heroContactButton: "Contact me",
    aboutTitle: "About Me",
    aboutParagraph1: "Initial experience in real development and team management projects. I led the Backend development at Valuat, achieving an improvement of up to 50% in endpoint performance compared to the previous technology and up to 30% in database calls. As a project manager, I provide service to two General Subdirectorates, managing teams from 3 different companies.",
    aboutParagraph2: "[Add more details if you wish, such as relevant interests, hobbies, or your work philosophy.]",
    projectsTitle: "Featured Projects",
    project1AltImage: "[Image of Project 1]",
    project1Title: "Web Test Service",
    project1Desc: "Developed with Laravel, PHP, MySQL, MongoDB.",
    project2AltImage: "[Image of Project 2]",
    project2Title: "Data Statistics Web Scripting",
    project2Desc: "Developed with Python, Xampp, MySQL.",
    project3AltImage: "[Image of Project 3]",
    project3Title: "IoT Device Simulation",
    project3Desc: "Developed with Python, Google Cloud, HTML5, CSS3, JS, MariaDB.",
    projectSeeMore: "See more",
    projectSourceCode: "Source Code",
    experienceTitle: "Work Experience",
    exp1Title: "IT Project Manager - Ministry of Housing and Urban Agenda",
    exp1Dates: "October 2024 - Present",
    exp1Task1: "Coordinate 4 work teams belonging to 3 different companies in development, maintenance, and support that provide service to 2 General Subdirectorates.",
    exp1Task2: "Participate in process improvement through the implementation of methodologies that allow for greater efficiency and speed in the development, support, and maintenance tasks of the different work teams.",
    exp1Task3: "Manage the necessary actions for system maintenance in collaboration with the specialized systems and communications team.",
    exp1Task4: "Analyze current tools and solutions to find improvements to implement in the systems, mainly related to performance and user experience.",
    exp1Task5: "Design reports that provide a practical general view of each of the IT systems and managed teams.",
    exp1Task6: "Prepare statistics using the Google Analytics tool, as part of system management with annualized information and the preparation of personalized reports.",
    exp2Title: "Backend Developer - Valuat",
    exp2Dates: "November 2021 - February 2023",
    exp2Task1: "Implemented the Scrum work methodology with development in two-week sprints that allowed for greater efficiency and speed.",
    exp2Task2: "Improved the overall efficiency of the Backend system by up to 35% compared to the old system, based on analysis and design.",
    exp3Title: "Intern IT Systems Manager - National Institute of Public Administration",
    exp3Dates: "June 2024 - October 2024",
    exp3Task1: "Practice-oriented training",
    exp3Task2: "Course on Data Governance and Equality",
    skillsTitle: "Skills",
    skillsTechTitle: "Technical Skills",
    skillsOtherTech: "[Other Skill]",
    skillsLangTitle: "Languages",
    skillsLangSpanish: "Spanish:",
    skillsLangSpanishLevel: "Native",
    skillsLangEnglish: "English:",
    skillsLangEnglishLevel: "Fluent",
    skillsLangOther: "[Other Language]:",
    skillsLangOtherLevel: "[Level]",
    skillsToolsTitle: "Tools",
    skillsSoftTitle: "Soft Skills",
    skillsSoftComm: "Communication",
    skillsSoftTeam: "Teamwork",
    skillsSoftProblem: "Problem Solving",
    skillsSoftAdapt: "Adaptability",
    contactTitle: "Contact",
    contactIntro: "Interested in learning more? Feel free to contact me!",
    contactDownloadPrompt: "You can also download my CV:",
    contactMail: "Contact me",
    contactDownloadButtonES: "Download CV (Spanish)",
    contactDownloadButtonEN: "Download CV",
    footerRights: "© 2025 Marcos Díaz Oliva. All rights reserved.",
    contactFormTitle: "Get in Touch",
    contactFormIntro: "Have a question or proposal? Fill out the form.",
    contactFormLabelName: "Full Name",
    contactFormInputName: "Your full name",
    contactFormLabelMail: "Email address",
    contactFormInputMail: "you@email.com",
    contactFormLabelPhone: "Phone number",
    contactFormLabelOptional: "(Optional)",
    contactFormInputPhone: "+1 555 000 0000",
    contactFormLabelMessage: "Message",
    contactFormInputMessage: "Write your inquiry or message here...",
    contactFormSend: "Send",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
  }
};